import type {Metadata} from 'next';
import Link from 'next/link';
import './globals.css';
import { Toaster } from "@/components/ui/toaster"
import { FirebaseClientProvider } from '@/firebase/client-provider';
import { Button } from '@/components/ui/button';

export const metadata: Metadata = {
  title: 'Blogify',
  description: 'Generated by Firebase Studio',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet" />
      </head>
      <body className="font-body antialiased h-full flex flex-col">
        <FirebaseClientProvider>
          <div className="flex-grow">
            {children}
          </div>
        </FirebaseClientProvider>
        <footer className="py-4 border-t">
          <div className="container mx-auto flex justify-center items-center">
            <Button variant="link" asChild>
              <Link href="/admin">Admin Portal Login</Link>
            </Button>
          </div>
        </footer>
        <Toaster />
      </body>
    </html>
  );
}
